name: OOMMFPy multi-platform publish

on:
  workflow_dispatch:
    branches: [ test_gh_actions ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.7]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
